# Generated by Django 3.2.8 on 2021-12-06 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyportal', '0003_auto_20211205_2243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
